import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs'; import path from 'path';
const types = { '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript', '.wasm': 'application/wasm', '.json': 'application/json', '.webmanifest': 'application/manifest+json', '.png': 'image/png', '.tflite': 'application/octet-stream', '.task': 'application/octet-stream' };
const srv = http.createServer((q, r) => { const u = q.url.split('?')[0]; if (u === '/' || u === '/index.html') { r.writeHead(200, { 'content-type': 'text/html' }); return r.end(fs.readFileSync('dist/index.html')); } const f = path.join('public', u); if (!f.startsWith('public') || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { r.writeHead(200, { 'content-type': 'text/html' }); return r.end(fs.readFileSync('dist/index.html')); } r.writeHead(200, { 'content-type': types[path.extname(f)] || 'application/octet-stream' }); r.end(fs.readFileSync(f)); }).listen(8186);
const yuv = process.env.Y4M || '/tmp/face.y4m';
const b = await chromium.launch({ args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--use-file-for-fake-video-capture=' + yuv, '--no-sandbox', '--allow-loopback-in-peer-connection', '--autoplay-policy=no-user-gesture-required'] });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fail = 0; const ok = (n, c) => { console.log(c ? 'PASS' : 'FAIL', n); if (!c) fail++; };
const c = await b.newContext({ viewport: { width: 420, height: 820 } }); const A = await c.newPage(); A.on('pageerror', (e) => console.log('ERR', e.message));
await A.goto('http://localhost:8186/'); await A.uncheck('#approve'); await A.click('#create'); await A.click('#cam'); await wait(2500);
await A.click('#more'); await A.selectOption('#face', 'bgblur'); await wait(1500);
const early = await A.evaluate(() => window.__pr.seg); console.log('seg early', early);
await wait(9000);
const st = await A.evaluate(() => ({ seg: window.__pr.seg, seen: window.__pr.segSeen, err: window.__pr.segErr }));
console.log(JSON.stringify(st)); ok('segmenter loaded and produced a mask', st.seg === 'ready' && st.seen === true);
const res = await A.evaluate(() => { const cv = window.__pr.faceCanvas; const x = cv.getContext('2d'); const w = cv.width, h = cv.height;
  const sharp = (x0, y0, ww, hh) => { const d = x.getImageData(x0, y0, ww, hh).data; let s = 0; for (let i = 4; i < d.length - 4; i += 4) s += Math.abs(d[i] - d[i - 4]); return s / (d.length / 4); };
  return { w, h, centre: sharp(Math.round(w * .35), Math.round(h * .3), Math.round(w * .3), Math.round(h * .3)), corner: sharp(0, 0, Math.round(w * .2), Math.round(h * .2)), url: cv.toDataURL('image/png') }; });
fs.writeFileSync('/tmp/bgblur.png', Buffer.from(res.url.split(',')[1], 'base64'));
console.log('sharpness centre', res.centre.toFixed(2), 'corner', res.corner.toFixed(2)); ok('person sharper than background', res.centre > res.corner * 1.3);
await A.screenshot({ path: '/tmp/dark.png' });
await A.click('#theme'); await wait(400); const th = await A.evaluate(() => ({ t: document.documentElement.dataset.theme, ls: localStorage.getItem('mut3d-theme'), bg: getComputedStyle(document.body).backgroundColor }));
console.log(JSON.stringify(th)); ok('theme toggles and persists', th.t === 'light' && th.ls === 'light');
await A.click('#more'); await wait(300); await A.screenshot({ path: '/tmp/light.png' });
await A.reload(); await wait(800); ok('theme survives reload', await A.evaluate(() => document.documentElement.dataset.theme) === 'light');
console.log(fail ? 'FAILED ' + fail : 'ALL PASS'); await b.close(); srv.close(); process.exit(fail ? 1 : 0);
