import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs';
const srv = http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(fs.readFileSync('dist/index.html')); }).listen(8170);
const b = await chromium.launch({ args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--no-sandbox', '--allow-loopback-in-peer-connection', '--auto-select-desktop-capture-source=Entire screen'] });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fail = 0; const ok = (n, c) => { console.log(c ? 'PASS' : 'FAIL', n); if (!c) fail++; };
const mk = async (u) => { const c = await b.newContext({ acceptDownloads: true }); const p = await c.newPage(); await p.goto(u); return p; };
const A = await mk('http://localhost:8170/'); await A.fill('#name', 'Ann'); await A.click('#create'); const url = A.url(); await A.click('#cam'); await wait(2500);
const B = await mk(url); await B.fill('#name', 'Bo'); await B.click('#cam');
const C = await mk(url); await C.click('#nocam');
await wait(14000);
ok('A sees 2 peers', await A.evaluate(() => window.__pr.conns.size) === 2);
ok('3 tiles on B', await B.evaluate(() => document.querySelectorAll('figure').length) === 3);
ok('name shown', (await B.textContent('#videos')).includes('Ann'));
ok('remote video playing', await B.evaluate(() => [...document.querySelectorAll('video')].filter((v) => v.videoWidth > 0).length) >= 2);
await A.click('#chatbtn'); await A.fill('#msg', 'hello <b>x</b>'); await A.press('#msg', 'Enter'); await wait(1500);
ok('chat arrives, escaped', (await B.textContent('#log')).includes('hello <b>x</b>') && await B.evaluate(() => !document.querySelector('#log b b')));
await A.click('#mic'); await wait(1500);
ok('mute shown remotely', (await B.textContent('#videos')).includes('🔇'));
await A.click('#camb'); await wait(1500);
ok('cam off shown', (await B.textContent('#videos')).includes('off'));
fs.writeFileSync('/tmp/t.bin', Buffer.from(Array.from({ length: 100000 }, (_, i) => i % 251)));
await A.setInputFiles('#file', '/tmp/t.bin'); await wait(3000);
await B.click('#chatbtn');
const [dl] = await Promise.all([B.waitForEvent('download', { timeout: 8000 }).catch(() => null), B.click('#log a').catch(() => {})]);
if (dl) { const p = await dl.path(); ok('file identical', fs.readFileSync(p).equals(fs.readFileSync('/tmp/t.bin'))); } else ok('file download', false);
await B.click('#share'); await wait(3000);
ok('screen share flagged', (await A.textContent('#videos')).includes('🖥'));
// reconnect: C drops and rejoins
await C.close(); await wait(22000);
ok('A notices leave', await A.evaluate(() => window.__pr.conns.size) === 1);
const C2 = await mk(url); await C2.click('#nocam'); await wait(15000);
ok('rejoin works', await A.evaluate(() => window.__pr.conns.size) === 2);
console.log(fail ? 'FAILED ' + fail : 'ALL PASS'); await b.close(); srv.close(); process.exit(fail ? 1 : 0);
