import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs';
http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(fs.readFileSync('dist/index.html')); }).listen(8170);
const b = await chromium.launch({ args: ['--no-sandbox', '--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'] });
const mk = async () => (await b.newContext()).newPage();
const res = []; const ok = (n, v, x) => { res.push(v); console.log(v ? 'PASS' : 'FAIL', n, x || ''); };
const A = await mk(); await A.goto('http://localhost:8170/'); await A.click('#create'); const url = A.url(); await A.click('#nocam'); await A.waitForTimeout(1500);
const B = await mk(); await B.goto(url); await B.click('#nocam'); await B.waitForTimeout(7000);
const vids = (p) => p.evaluate(() => [...document.querySelectorAll('#videos video')].map((v) => v.videoWidth + 'x' + v.videoHeight + (v.paused ? 'P' : '')));
ok('A and B see 2 playing videos', (await vids(A)).length === 2 && (await vids(B)).length === 2, JSON.stringify([await vids(A), await vids(B)]));
await B.reload(); await B.click('#nocam'); await B.waitForTimeout(12000);
const st = await B.textContent('#status'); const va = await vids(A), vb = await vids(B);
ok('B rejoined after refresh', /In the room as/.test(st), st);
ok('after refresh both see 2 videos', va.length === 2 && vb.length === 2, JSON.stringify([va, vb]));
ok('no black/zero-size video after refresh', va.every((x) => !x.startsWith('0x')) && vb.every((x) => !x.startsWith('0x')), JSON.stringify([va, vb]));
await A.evaluate(() => window.__pr.doc.getText('code').insert(0, 'hello')); await B.waitForTimeout(1500);
ok('doc syncs after refresh', (await B.evaluate(() => window.__pr.doc.getText('code').toString())).includes('hello'));
console.log(res.every(Boolean) ? 'REJOIN PASS' : 'REJOIN FAIL'); process.exit(0);
