import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs';
const srv = http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(fs.readFileSync('dist/index.html')); }).listen(8171);
const b = await chromium.launch({ args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--no-sandbox', '--allow-loopback-in-peer-connection', '--auto-select-desktop-capture-source=Entire screen'] });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
let fail = 0; const ok = (n, c) => { console.log(c ? 'PASS' : 'FAIL', n); if (!c) fail++; };
const mk = async (u) => { const c = await b.newContext({ acceptDownloads: true }); const p = await c.newPage(); await p.goto(u); return p; };
const A = await mk('http://localhost:8171/'); await A.fill('#name', 'Ann'); await A.uncheck('#approve'); await A.click('#create'); const url = A.url(); await A.click('#cam'); await wait(2500);
const P = [A];
for (let i = 1; i < 6; i++) { const x = await mk(url); await x.fill('#name', 'P' + i); if (i % 2) await x.click('#cam'); else await x.click('#nocam'); P.push(x); await wait(2500); }
await wait(25000);
ok('all 6 see 5 peers', (await Promise.all(P.map((p) => p.evaluate(() => window.__pr.conns.size)))).every((n) => n === 5));
ok('6 tiles each', (await Promise.all(P.map((p) => p.evaluate(() => document.querySelectorAll('figure').length)))).every((n) => n === 6));
ok('remote video playing on A', await A.evaluate(() => [...document.querySelectorAll('video')].filter((v) => v.videoWidth > 0).length) >= 3);
const br = await A.evaluate(() => { const out = []; for (const c of window.__pr.calls ? window.__pr.calls.values() : []) { for (const s of c.peerConnection.getSenders()) if (s.track && s.track.kind === 'video') out.push(s.getParameters().encodings[0].maxBitrate); } return out; });
console.log('send maxBitrate per peer:', JSON.stringify(br));
await P[1].click('#chatbtn'); await P[1].fill('#msg', 'six'); await P[1].press('#msg', 'Enter'); await wait(2500);
ok('chat reaches all', (await Promise.all([A, P[3], P[5]].map(async (p) => { await p.click('#chatbtn').catch(() => {}); return (await p.textContent('#log')).includes('six'); }))).every(Boolean));
const G = await mk(url); await G.click('#nocam'); await wait(20000);
ok('7th sees room full', (await G.textContent('#status')).includes('full'));
console.log(fail ? 'FAILED ' + fail : 'ALL PASS'); await b.close(); srv.close(); process.exit(fail ? 1 : 0);
