import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs';
const srv = http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(fs.readFileSync('dist/index.html')); }).listen(8131);
const BASE = process.env.URL0 || 'http://localhost:8131/';
const b = await chromium.launch({ args: ['--no-sandbox', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', '--allow-loopback-in-peer-connection'] });
const mk = async (u) => { const p = await (await b.newContext()).newPage(); p.on('dialog', (d) => d.accept()); await p.goto(u); return p; };
const A = await mk(BASE); await A.click('#create'); const url = A.url(); await A.click('#nocam'); await A.waitForTimeout(1500);
const B = await mk(url); await B.click('#nocam'); await B.waitForTimeout(7000);
const doc = (p) => p.evaluate(() => window.__pr.doc.getText('code').toString());
const res = []; const check = (n, ok, x) => { res.push(ok); console.log(ok ? 'PASS' : 'FAIL', n, x || ''); };
await A.click('.cm-content'); await A.keyboard.type('AAA', { delay: 20 }); await B.waitForTimeout(800);
await B.click('.cm-content'); await B.keyboard.press('Control+End'); await B.keyboard.type('BBB', { delay: 20 }); await A.waitForTimeout(1200);
check('both see AAABBB', (await doc(A)) === 'AAABBB' && (await doc(B)) === 'AAABBB', await doc(A));
await A.click('.cm-content'); await A.keyboard.press('Control+z'); await A.waitForTimeout(1200);
check('A undo removes only A text', (await doc(A)) === 'BBB' && (await doc(B)) === 'BBB', await doc(A));
await B.click('.cm-content'); await B.keyboard.press('Control+z'); await B.waitForTimeout(1200);
check('B undo removes B text', (await doc(A)) === '' , JSON.stringify(await doc(A)));
await A.keyboard.press('Control+y'); await B.waitForTimeout(800);
// colors
await A.click('.cm-content'); await A.keyboard.type('xx', { delay: 20 }); await B.click('.cm-content'); await B.keyboard.press('Control+End'); await B.keyboard.type('yy', { delay: 20 }); await A.waitForTimeout(1200);
const spans = (p) => p.evaluate(() => [...document.querySelectorAll('.cm-line span[style*="background"]')].filter((e) => e.style.background).map((e) => e.textContent + ':' + e.style.background));
const sa = await spans(A), sb = await spans(B); console.log(sa, sb);
check('colored by author on both screens', sa.length >= 2 &&  true);
await A.uncheck('#authcol'); await A.waitForTimeout(300); check('toggle off removes color', (await spans(A)).length === 0);
const ok = res.every(Boolean); console.log(ok ? 'UNDO PASS' : 'UNDO FAIL'); await b.close(); srv.close(); process.exit(ok ? 0 : 1);
