import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs';
const srv = http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(fs.readFileSync('dist/index.html')); }).listen(8129);
const BASE = process.env.URL0 || 'http://localhost:8129/';
const b = await chromium.launch({ args: ['--no-sandbox', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream', '--allow-loopback-in-peer-connection'] });
const mk = async (u) => { const p = await (await b.newContext()).newPage(); p.on('dialog', (d) => d.accept()); await p.goto(u); return p; };
const A = await mk(BASE); await A.click('#create'); const url = A.url(); await A.click('#nocam'); await A.waitForTimeout(1500);
const B = await mk(url); await B.click('#nocam'); await B.waitForTimeout(7000);
const doc = (p) => p.evaluate(() => window.__pr.doc.getText('code').toString());
await A.click('.cm-content'); await A.keyboard.type('version one', { delay: 10 }); await B.waitForTimeout(800);
await A.click('#cpsave'); await B.waitForTimeout(1200);
console.log('B sees checkpoint:', (await B.textContent('#cplist')).includes('Saved by hand'));
await B.click('.cm-content'); await B.keyboard.press('Control+End'); await B.keyboard.type(' plus B edits', { delay: 10 }); await A.waitForTimeout(1200);
console.log('doc now:', JSON.stringify(await doc(A)));
await A.click('#cplist button:has-text("Restore")'); await A.waitForTimeout(1500);
const dA = await doc(A), dB = await doc(B); console.log('after restore A:', JSON.stringify(dA), 'same:', dA === dB);
const n = await A.evaluate(() => window.__pr.doc.getMap('checkpoints').size); console.log('checkpoints:', n, '(hand + before-restore)');
const back = await B.evaluate(() => [...window.__pr.doc.getMap('checkpoints').values()].some((c) => c.text.includes('plus B edits')));
console.log('pre-restore state kept as checkpoint:', back);
const ok = dA === 'version one' && dB === dA && back; console.log(ok ? 'CP PASS' : 'CP FAIL'); await b.close(); srv.close(); process.exit(ok ? 0 : 1);
