import { chromium } from 'playwright'; import http from 'http'; import fs from 'fs';
http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(fs.readFileSync('dist/index.html')); }).listen(8150);
const b = await chromium.launch({ args: ['--no-sandbox'] });
const mock = `export const gpuInfo=async()=>({ok:true,f16:false});export const hasModel=()=>true;export const loadModel=async(id,cb)=>{cb('x',1)};let n=0;export const ask=async(m,cb)=>{n++;const u=m[m.length-1].content;const t='\`\`\`html\\n<!doctype html><html><body><script>document.title="V'+n+' '+(u.match(/like this: (.*)/)||[,''])[1].replace(/"/g,'')+'"</script></body></html>\\n\`\`\`';cb(t);return t};export const stop=()=>{}`;
const mk = async (u) => { const c = await b.newContext(); await c.addInitScript(() => { document.addEventListener('DOMContentLoaded', () => document.querySelectorAll('details').forEach((x) => x.open = true)); }); const p = await c.newPage(); await p.route('**/ai.js', (r) => r.fulfill({ contentType: 'text/javascript', body: mock })); await p.goto(u); return p; };
const res = []; const ok = (n, v, x) => { res.push(v); console.log(v ? 'PASS' : 'FAIL', n, x || ''); };
const A = await mk(process.env.URL0 || 'http://localhost:8150/'); await A.click('#create'); const url = A.url(); await A.click('#nocam'); await A.waitForTimeout(1500);
const B = await mk(url); await B.click('#nocam'); await B.waitForTimeout(7000);
await A.evaluate(() => { const d = window.__pr.doc.getText('code'); d.insert(0, '<!doctype html><html><body><script>document.title="base"</script></body></html>'); });
await A.waitForTimeout(800);
await A.fill('#onebox', 'make it faster'); await A.click('#build'); await A.waitForTimeout(6000);
ok('B sees request from Guest 1', (await B.textContent('#proplist')).includes('Guest 1 wants: make it faster'), (await B.textContent('#proplist')).slice(0, 120));
ok('doc unchanged by request', (await B.evaluate(() => window.__pr.doc.getText('code').toString())).includes('"base"'));
await B.fill('#onebox', 'add enemies'); await B.click('#build'); await B.waitForTimeout(1500);
ok('second request queued', (await A.textContent('#proplist')).includes('In line: Guest 2 wants: add enemies'), (await A.textContent('#proplist')).slice(0, 200));
await B.click('button:text-is("Preview")'); await B.waitForTimeout(800);
await B.click('button:text-is("Accept")'); await B.waitForTimeout(1500);
const t1 = await A.evaluate(() => window.__pr.doc.getText('code').toString());
ok('accepted replaced game for everyone', t1.includes('make it faster'), t1.slice(0, 120));
await B.waitForTimeout(9000);
const pl = await A.textContent('#proplist');
ok('queued one rebuilt and posted as new request', pl.includes('Guest 2 wants: add enemies') && !pl.includes('In line'), pl.slice(0, 200));
await A.click('button:text-is("Skip")'); await A.waitForTimeout(800);
ok('skip leaves game', (await A.evaluate(() => window.__pr.doc.getText('code').toString())).includes('make it faster'));
await A.click('#undolast'); await A.waitForTimeout(500);
ok('undo last change goes back to base', (await A.evaluate(() => window.__pr.doc.getText('code').toString())).includes('"base"'));
console.log(res.every(Boolean) ? 'REQ PASS' : 'REQ FAIL'); process.exit(0);
